### ISSUE TITLE
Fullscreen support?

### ISSUE THREAD

**Issue by Ebirux** [r00telement/SmartHunter#2]
Could this mod support full-screen?

**Comment by r00telement** [comment]
It would require hooking into the game's dx device and using that to render directly into it. It's outside the scope of this project.

**Comment by SwimmingTiger** [comment]
@Ebirux I have successfully added full screen support for this mod, you can try the debug build here:
https://github.com/SwimmingTiger/SmartHunter/releases

@r00telement I added full screen support for this mod with these steps:
1. Create a dll that can be injected into the game and it will become a display server to draw UI to the game. [OverlayDisplayServer](https://github.com/SwimmingTiger/OverlayDisplayServer)
2. Implement the client of the above display server in SmartHunter to draw the UI on the game.
3. Inject the dll through a script and launch SmartHunter (this can be achieved in the future through SmartHunter itself so no longer need a script).

![Smart Hunter as a client of ODS](https://user-images.githubusercontent.com/4986069/58651372-b5f09080-8343-11e9-9614-992d89a545e4.png)

The lower right corner is drawn directly for the C# application (occluded in full screen gaming). In the upper left corner of the game is drawn through OverlayDisplayServer (visible in full screen gaming).

Although it has limited functionality (missing team widget and some others) and a simple UI, it works fine. Now I can finally make my G-Sync compatibility work again. (G-Sync compatibility has the very bad support for borderless window mode with a out-game overlay, it even enhances the tear. It works well with in-game overlay.)

@r00telement I want to know if you are considering merging my changes when I finished all parts of UI on fullscreen overlay (It will become a optional feature and will not be enabled by default). If you don't consider merging my changes, can I publish it separately? (I noticed this on NexusMod: `You are not allowed to modify my files, including creating bug fixes or improving on features under any circumstances.`)

**Comment by Ebirux** [comment]
@SwimmingTiger This is amazing! The only issue I'm running is alt tabbing = crash. Whenever I run that run.bat, it always alt tabs from the game and causes a crash.

**Comment by r00telement** [comment]
Neat, thanks for the heads up. I'll take a closer look later, but my primary concerns for this are 1) performance, and 2) visual parity, because the in game render seems to be quite different to the window renders, going by the screenshots.

I've been working on a proof of concept for a fully native, injected version of SmartHunter that will look and function identically to the WPF version, built for performance, full screen rendering, and allowing for spatial UI. No idea when it will be available though.

In terms of merging/publishing separately, I'll get back to you on that :)

**Comment by SwimmingTiger** [comment]
@Ebirux Because my dll hardcoded the font, if the system lacks the `simhei.ttf` font file, executing `run.bat` will cause the game to crash immediately. You can consider adding the `Simplified Chinese (China)` language pack to your system or download `simhei.ttf` on the Internet and put it into `C:\Windows\Fonts` to temporarily solve the problem. The dependency on `simhei.ttf` will be removed later.

@r00telement The in-game render is completely reimplemented based on [dear imgui](https://github.com/ocornut/imgui) ([this](https://github.com/SwimmingTiger/SmartHunter/blob/dev/SmartHunter/Ui/Remote/lua/render.lua) is the render's code), I just roughly mimicked the style of C# UI. Dear imgui is a mature in-game GUI solution that I believe can achieve the same rendering effects as the current C# UI.

I think performance is not a problem. The amount of data transmitted through the local loopback is small, and the transmission and rendering are asynchronous. Even with the debug version, I haven't noticed a significant frame rate reduction.

**Comment by SwimmingTiger** [comment]
And for a fully native, injected version of SmartHunter, I think [Indicium-Supra](https://github.com/nefarius/Indicium-Supra) is a good starting point. It simplifies the implementation of in-game overlays. [Indicium-ImGui](https://github.com/nefarius/Indicium-Supra/tree/master/samples/Indicium-ImGui) is also a good sample of in-game GUI rendering (my DLL implementation is modified from this sample).

In addition, if you already have some codes of the fully native version, I am happy to participate in the development.

**Comment by r00telement** [comment]
Imgui is super dated and doesn't support the sort of modern UI features that SmartHunter takes advantage of - things like declarative styles, templating, vector graphics, animation, MVVM... And using such a solution means that none of the UI from the WPF project can be reused. Not to mention a regression on the whole skinning capability.

It's essential that the native project uses XAML, which is why it's based on [NoesisGUI](https://www.noesisengine.com/). This is pretty damn close to WPF in its use with a few gotchas here and there, but in terms of modern UI, it's second to none. So with that in mind, I'm not approaching the native project like a typical rough looking hack that you'd find for other games, but with a bit of care - like a sort of AAA extension to the in-game UI.

I'll try to get the source cleaned up and on github in the next couple weeks (little slow because I'm busy with other things at the moment). It'll begin its life privately but I'd be happy to throw you an invite if you'd like. Do you use Discord?

**Comment by SwimmingTiger** [comment]
Yes I have a Discord `SwimmingTiger#5712`.

**Comment by SwimmingTiger** [comment]
@Ebirux A new debug build has been released, and I think it should no longer crash due to missing fonts.
https://github.com/SwimmingTiger/SmartHunter/releases/tag/ods-0.1.4

![Smart Hunter as a client of ODS](https://user-images.githubusercontent.com/4986069/58766491-eb021a80-85b1-11e9-9cd4-7f65e4ee463c.png)

The monster widget on the top is rendering through OverlayDisplayServer (visible in full screen gaming). And the second is rendering by the C# application itself (occluded in full screen gaming).

Note that the order of monsters in two monster widgets is different, because the ordering of Lua tables is uncertain. The timer in the upper left corner is 1 second longer than the timer in C# UI, because the `ceil()` function is used in Lua (Lua lacks a rounding function), which does not introduce too many errors.

I know it doesn't look modern, but it works and shows the information I need. This is enough for me. I will add Team Widget to it later.

**Comment by SwimmingTiger** [comment]
It seems that NoesisGUI does not have Lua or LuaJIT bindings, so there is no way for my display server to easily support it (otherwise I need to write my own LuaJIT binding) :rofl:
